In [ ]:
print("hi2")

In [7]:
import csv

def make_person_id(name):
    return name.lower().replace(' ','_').replace('.','').replace('(','').replace(')','').replace('-','') \
    .replace('"','').replace("'",'').replace('?','').replace('\\','').replace('’','').replace('“','') \
    .replace('”','')

with open('/Users/chadarmstrong/Library/Mobile Documents/com~apple~CloudDocs/Archive/Programming/Node/geneology_github/data/Geneology.csv') as csv_file:
    people = list(csv.DictReader(csv_file))

people[100:102]

[{'Name': 'Joy Ann Church',
  'Gender': 'Female',
  'Born': '6/16/1971',
  'Born Location': 'Berwick, PA',
  'Died': '',
  'Died Location': '',
  'Mother': '',
  'Father': '',
  'Married to': 'Randall Lee Murphy',
  'Married Date': '12/28/1996',
  'Married Location': 'Northumberland, PA',
  'Second Marriage to': '',
  'Second Marriage Date': '',
  'Second Marriage Location': '',
  'Third Marriage to': '',
  'Third Marriage Date': '',
  'Notes': 'Divorced on 10/4/2011',
  '': ''},
 {'Name': 'Hannah Joy Murphy',
  'Gender': 'Female',
  'Born': '9/16/2000',
  'Born Location': 'Lewisburg, PA',
  'Died': '',
  'Died Location': '',
  'Mother': 'Joy Ann Church',
  'Father': 'Randall Lee Murphy',
  'Married to': '',
  'Married Date': '',
  'Married Location': '',
  'Second Marriage to': '',
  'Second Marriage Date': '',
  'Second Marriage Location': '',
  'Third Marriage to': '',
  'Third Marriage Date': '',
  'Notes': '',
  '': ''}]

In [8]:
count = 34
for person in people:
    print(str(count) + ' ' + person['Name'])
    count = count + 1

34 Joseph Armstrong
35 Ann Waldron
36 Jehiel Armstrong
37 Rebecca Starks
38 Thomas Waldron Armstrong
39 Miles Aldridge Armstrong
40 Alida A. Adams
41 Frank Miles Armstrong
42 Alice M. Haskins
43 Walter Armstrong
44 Claude Armstrong
45 Pearl Armstrong
46 Aubrey Armstrong
47 Guy Armstrong
48 Richard (Dick) Harry Armstrong
49 Eleanor Bullock
50 Noela Griffin
51 Edgar Harry Armstrong
52 Christine Fae (“Tini”) Chaffee
53 Doris Armstrong
54 Melissa A. Armstrong Adams
55 Laura Jane Armstrong
56 Charles Wesley Mosher
57 Colleen Abigail Armstrong
58 Jerry Quick
59 Michael Edward Quick
60 Elizabeth Anne Quick
61 Edgar David Armstrong
62 Carol Marie Murphy
63 Chad David Armstrong
64 Michael David Killen
65 Cynthia Carson
66 Michael Killen
67 Brett Nolan Armstrong
68 Heather Dawn Seymour
69 Brielle Nicole Armstrong
70 Annika Noel Armstrong
71 Sean Patrick Armstrong
72 Renee Elizabeth Glick
73 Renaissance Lenore Armstrong
74 Mason Quade Armstrong
75 Timothy Lee Armstrong
76 Patricia Dyess
77 Timothy James Armstrong
78 Meredith Rae Armstrong
79 Justin Coffman
80 Callie Ann Armstrong
81 Tyler Lee Armstrong
82 Peter Jay Armstrong
83 Pamela Joy Armstrong
84 Jeffrey Dubert
85 Stephen Jeffrey Dubert
86 Michael Scott Dubert
87 Thomas Charles Armstrong
88 Laurie Potter
89 Michelle Lynn Armstrong
90 Sam J. Holder
91 Benjamin Thomas Armstrong
92 John Gregory Armstrong
93 Kelly Teeter
94 Sarah Elizabeth Armstrong
95 Bethany Grace Armstrong
96 Ashley Marie Armstrong
97 Joshua David Armstrong
98 Emily Rose Armstrong
99 Caleb John Armstrong
100 Daniel Jacob Armstrong
101 Daniel Jean (Jene) Murphy
102 Miriam Amanda Kleppinger
103 Paul Allen Murphy
104 Donna Jardine
105 Lynda LeFoll LeVasseur
106 Marc Thomas LeVasseur
107 Jonathan Alexander LeVasseur
108 Tamara Sue Murphy
109 Jeffrey Paul Murphy
110 Kevin Alan Webster
111 Lance Kevin Webster
112 Lyle Allen Webster
113 Lynn Carol Randall
114 Daniel Paul Murphy
115 Brandon Lee Murphy
116 Julie Ann Thompson
117 Morgan Brittney Murphy
118 Maxwell Storer
119 Miles Gerrish Murphy
120 Nicholas Thompson
121 Kathryn Millet
122 Abel Thompson
123 Martha Mae Murphy
124 Ronald Lee Murphy
125 Martha Ellen Oplinger
126 Randall Lee Murphy
127 Marilyn Irene Murphy
128 Rodney Lynn Murphy
129 Richard Lewis Murphy
130 Judy Anderson
131 Randall Cyril Murphy
132 Adrian Michael Murphy
133 Melody Ann Murphy
134 Joy Ann Church
135 Hannah Joy Murphy
136 Ryan Lee Murphy
137 Steven Earl Davis
138 James Fredrick Davis
139 Stefanie Nicole Davis
140 Cheri Hoffman
141 Rodney Lynn Murphy II
142 Ricky Lynn Murphy
143 Emily Ann Dettmer
144 Emma LeeAnn Murphy
145 Phyllis Ellen Murphy
146 Warren Lawrence Palmer
147 Kelly Lynn Palmer
148 Kevin Lee Palmer
149 Kyle Lane Palmer
150 Jody Todd Bliss
151 Shawn Rakchon Bliss
152 Cole Ratchasi Bliss
153 Rachel Elizabeth Smith
154 Lily Marie Bliss
155 Jean Leigh Avery
156 Derek Carver Palmer
157 Branden Cooper Palmer
158 Kathleen Wojnowicz-Kott
159 Mackenzie Morseman
160 Rosana Flordeliz Marcial
161 Ashley Nicole Palmer
162 Kayla Marie Palmer
163 Luke Marcial Palmer
164 Mark Elden Murphy
165 Diann Marie Semski
166 James Adam Murphy
167 Mathew Brennen Murphy
168 Janie Denise Barrett
169 Alexander James Murphy
170 Haven Lu Murphy
171 Hope Noelle Murphy
172 Karen Sue Davis
173 Jason Owen Murphy
174 Levi Jonathan Murphy
175 Sarah Mae Murphy
176 Hannah Rae Murphy
177 Gene Elbert Murphy
178 Vada Mae Smith
179 Martha Honsberger
180 Karen Mae Murphy
181 Daniel Gene Murphy
182 Jaime Lynn Murphy
183 Matthew Thomas Slezak
184 Kaitlyn Mae Slezak
185 Jonathan Thomas Slezak
186 Erika Joy (Clark) Jones
187 Logan Xavier Murphy
188 Kurt William Sickinger
189 Colin Murphy Sickinger
190 Molly Murphy Sickinger
191 Mary Ann Murphy
192 Franklin James Smalley
193 Tara Mae Smalley
194 Tighe James Smalley
195 Tobiah Nathaniel Smalley
196 Trevor Lee Smalley
197 Nathan James Reimer
198 Alexander Nathaniel Reimer
199 Ainslie Elisabeth Reimer
200 Adeline Reese Reimer
201 Jessica Kristen Shannon
202 Elenna Marie Kuhn
203 Hannah Ruth Hesed Forbes
204 Larry Ray Murphy
205 Linda Lou Barber
206 Alice Elizabeth Murphy
207 Denise Lynn Murphy
208 Matt Gibson
209 Darrian Amanda Gibson
210 Jaden Reese Gibson
211 Todd William Day
212 Brenen Daniel Todd Murphy
213 Ethan William Day
214 Andrew Scott Evans
215 Scott Evans
216 John Daniel Murphy
217 Rhonda Kay Patterson
218 Joshua John Murphy
219 Rosa Hong
220 Logan Joshua Murphy
221 Isabel Rose Murphy
222 John George Kleppinger
223 Ludwig Kleppinger
224 Lewis Kleppinger
225 David Kleppinger
226 Lovina Kuntz
227 Catherine Cordelia Kleppinger
228 Louisa H. Kleppinger
229 Thomas M. Gable
230 Joseph H. Kleppinger
231 Mary Gemmel
232 Annie M.E. Kleppinger
233 John Newhard
234 Charles Kleppinger
235 James M. Kleppinger
236 Marietta Boyer
237 George Herman Kleppinger
238 Clara S. Wilson
239 Thomas M. Kleppinger
240 Lena M. Peiffley
241 Sarah E. Kleppinger
242 Albert D. George
243 Nellie George
244 Dr. Nathaniel Ritter
245 William David Kleppinger (first)
246 Adina Rebecca Kleppinger
247 Franklin Sylvester Dreisbach
248 Jeremiah Wilson Kleppinger
249 Amanda R. Hummel
250 Matilda (Solt) Humel
251 William H. Humel
252 William David Kleppinger
253 Wallace Edgar Kleppinger
254 Sallie B. Clymer
255 Ernest Jeremiah Oplinger
256 Minnie May Kleppinger
257 Edward C. Oswald
258 Harold Kleppinger Oswald
259 Marguerite McQuilken
260 Jean Louise Oswald
261 Ray C. Gilbert
262 Cheryl Ann Gilbert
263 Pauline A. Oswald
264 Alton F. Wagaman
265 Elaine Lois Wagaman
266 Frank Franz
267 Laura Estella Kleppinger
268 Newton J. Oplinger
269 Gladys Estella Oplinger
270 C. Leon Dieter
271 Carl Leon Dieter
272 Lucille Doris Dieter
273 Jean Ruth Dieter
274 Lloyd J. Liggitt
275 James Leon (Jimmy) Liggitt
276 Ronald Earl Liggitt
277 Larry Lee Liggitt
278 Paul David Dieter
279 Jane Price
280 David Dean Dieter
281 Vincent Newton Dieter
282 John Oplinger
283 Florence Nora Oplinger
284 Gilbert J. Ziegenfuss
285 Alton David Ziegenfuss
286 Naomi G. Kleppinger
287 Joan Dorothy Ziegenfuss
288 Dorothy Remley
289 Sandra Jean Oplinger
290 Suzanne Dorothy Oplinger
291 Elsie Jane Kleppinger
292 Victor E. Schaeffer
293 Elvin Roy Schaffer
294 Pearl Mae Buss
295 Sheila Mae Schaffer
296 Neil Roy Schaffer
297 Eileen Schaffer
298 Isabel Mary Shaffer
299 Matthew E. Givler
300 Robert L. Benner
301 Harry Lewis Kleppinger
302 Eva R. Manbeck
303 Eugene Manbeck Kleppinger
304 Jane Houser
305 Geneva Mae Kleppinger
306 Kathy Jane Kleppinger
307 Harry Earl Kleppinger
308 May Amanda Kleppinger
309 Eugene Filbert
310 Foster Gerhard
311 Roy Edward Kleppinger
312 Dorothy Morgan
313 Ruth Naomi Kleppinger
314 Elwood A. Vack
315 Donald Jesse Vack
316 Nora Alice Kleppinger
317 Warren W. Wehr
318 Evelyn Alice Wehr
319 Donald Lewis Wehr
320 Harriet Butz
321 Arline Fay Wehr
322 Pauline May Wehr
323 Berdie B. Yenser
324 Frank Albert Kleppinger
325 Sally Florence Schappell
326 Russell Alfred Kleppinger
327 Annabelle Russell
328 Donald Ray Kleppinger
329 Janet Kay Kleppinger
330 Keith Russell Kleppinger
331 Arthur Jeremiah Kleppinger
332 Ethel York
333 Gloria Ray Kleppinger
334 Richard Arthur Kleppinger
335 Wesley Albert Kleppinger
336 Eugene David Kleppinger
337 Willard David Kleppinger
338 Maxine Sypolt
339 Dawn Elaine Kleppinger
340 David J. Jalosky
341 Daryl D. Jalosky
342 Joyce Gay Kleppinger
343 Patti Kleppinger
344 Robert Jesse Kleppinger
345 Betty Jean Smith
346 Karen Kay Kleppinger
347 Robert Keith Kleppinger
348 David Merrill Kleppinger
349 Homer Kleppinger
350 Ruth Elizabeth Kleppinger
351 Wilson D. Miller
352 Leonard Wilson Miller
353 Bonnie Ruth Miller
354 Barry Lee Miller
355 Sally Ann Miller
356 Glenn Dale Miller
357 Bruce Allen Miller
358 Brian Carson Miller
359 Thomas Charles Chaffee
360 Mary Emma Palmer
361 Maynard Thomas Chaffee
362 Vivian Wright
363 Elbert Basil “Punk” Chaffee
364 Gertrude Ernestine Lundgren
365 Doris Mae “Dor” Chaffee
366 Stanley Delos Henry
367 Mary Pauline “Pauline” or “Deed”  Chaffee
368 Raymond Tompkins
369 Madge Elaine Chaffee
370 Charles Wilson
371 Charlotte Evelyn “Char" Chaffee
372 Donald Eugene Philips
373 Phyllis Wealthy “Phyl” Chaffee
374 Robert LeRoy Tompkins
375 La Verna Estelle Chaffee
376 John Adams
377 Richard Scott “Scotty” Adams
378 Sandy Cook
379 Scotty Adams
380 Julie Adams
381 David John Adams
382 Widi Adams
383 Michael David Adams
384 John Ellsworth Adams Jr.
385 Kimberlee Ann Adams
386 Chris Stamberger
387 Thayne Maxwell “Max” Stamberger
388 Phillip Maynard Chaffee
389 Shirley Hayes
390 Deborah Ann “Debi” Chaffee
391 Donald Swearingen
392 Tammy Jo Swearingen
393 Kyle Swearingen
394 Steven Michael Chaffee
395 James Andrew Chaffee
396 Sandy Beardsley
397 Jason Chaffee
398 Susan Stockham
399 Thomas Maynard Chaffee
400 Joann Chaffee
401 Amanda Chaffee
402 Nicole Chaffee
403 Brandon Chaffee
404 Debbie Hall
405 Pixie Lott
406 Terrance Newman “Terry” Chaffee
407 Dorothy Cortez
408 Carol Ann Chaffee
409 Terrance Newman Chaffee Jr.
410 Michael Chaffee
411 Thomas Ira Chaffee
412 Betty Lauerback
413 Jan Chaffee
414 Julie Rose Chaffee
415 Thomas Ira Chaffee Jr.
416 Anna Jo Chaffee
417 Judith Fay “Judy” Chaffee
418 Ronald L. Steve
419 Terry Lee Steve
420 Daniel Louis Steve
421 Veronica Steve
422 Vicki Steve
423 Brooks Hendrix
424 Jesse Steve
425 Amber Steve
426 Jo Ann Chaffee
427 Thomas Morse
428 Timmy Morse
429 Susan Morse
430 Bonnie Morse
431 Penny Marie Morse
432 John Stanley “Jack” Chaffee
433 Janet Bolt
434 Alan Charles Chaffee
435 Helen Miller
436 Mary Emma Palmer “Mamie” Chaffee
437 Dana Elliott Weed
438 Seth Andrew Charles Chaffee
439 Ethan William Palmer Chaffee
440 Charity Lynn Rager
441 Titus Easton Chaffee
442 Robert Earnest “Bob” Chaffee
443 Ann Rothermich
444 Desmond Stanley Henry
445 Mary Lou Bower
446 Terry Michael Henry
447 Todd Andrew Henry
448 Desiree Ann Henry
449 Maureen Anne Henry
450 Marie Alane Henry
451 Brian Thomas Henry
452 Brett Anthony Henry
453 Dennis Michael “Denny Mike” Henry
454 Julia Alliene (Judy) Fenner
455 Darlene Marie Henry
456 David Allen McMillen
457 David Allen McMillen Jr.
458 Katie McMillen
459 Brandon Michael McMillen
460 Cassie Alliene McMillen
461 Sierra Lynn ??
462 James Edward Henry
463 Tina Louise Bordenett
464 Cale James Henry
465 Sierra Lynn Henry
466 Stanley Richard Henry
467 Joseph Michael Burbee Henry
468 Kathleen Kaye “KK” Henry
469 Bernard Baldwin
470 David Ronald Harrington
471 Robert Corrington
472 Hollace “Holly” Ardelle Henry
473 Kathleen “Kathy” Elizabeth Henry
474 Stanley James Orr
475 Willard A. Newman
476 Marion Wayne Correll
477 Vikki Lynn Orr
478 James Deloss Orr
479 Belinda Leigh Orr
480 Michelle Elizabeth Newman
481 Holly Rene Newman
482 Jordan Kaveh Orr
483 Justin Khalil Orr
484 Jarel Lamont Orr
485 Jhavonte Aasin Moon
486 Aaliyah Dorisa Lucas
487 Amare Andre Lucas
488 Mary Jo Wilson
489 David Austic
490 Gene Cobb
491 Jacob Cobb
492 Michael Green Phillips
493 Rebecca Lou “Becky” Tompkins
494 Gilbert Norris
495 Jennifer Lyn Norris
496 Scott Nagell
497 Liam Robert Nagell
498 Christopher Nagell
499 Cavan Nagell
500 Braden Nagell
501 Daniel Robert Tompkins
502 Randy Lee Tompkins
503 Fae Elaine Hovencamp
504 Nathan Lee Tompkins
505 Kim Conroy
506 Alora Piper
507 Vicky Tompkins
508 Brenda Fairbanks
509 Ian Robert Tompkins
510 Lucienne Binkerd-Dale
511 Emily Fae Tompkins
512 Nancy Ann Minturn
513 Theodore “Theo” Ivory
514 Abby Deanne Tompkins
515 Michael John Hubbell
516 Erin Lee Spicer
517 Gabriel Jet Hubbell
518 Polly Ann Tompkins
519 Joe Taricska
520 Michael Robert Taricska
521 Emmalee O’Donnell
522 Brian Joseph Taricska
523 Candace Loreen Armstrong

In [ ]:
for person in people:
    print("CREATE (" + make_person_id(person['Name']) + \
    ":Person {name:'" + person['Name'] + "', birth_date:'" + person['Born'] + "', birth_location:'" + \
person['Born Location'] + "', death_date:'" + person['Died'] + "', death_location:'" + person['Died Location'] + "'})")

In [ ]:
print(people[1])

In [ ]:
print('Joseph Armstrong'.lower().replace(' ','_'))

In [ ]:
person = people[3]
print(person)

In [ ]:
def make_person_id(name):
    return name.lower().replace(' ','_').replace('.','').replace('(','').replace(')','').replace('-','') \
    .replace('"','').replace("'",'').replace('?','').replace('\\','')

In [ ]:
last_relationship = None

for person in people[40:90]:
    p = make_person_id(person['Name'])
    m = make_person_id(person['Mother'])
    f = make_person_id(person['Father'])
    s = make_person_id(person['Married to'])

    if person['Mother'] is not '':
        print("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'".format(m,p,m,person['Mother'],p,person['Name']))
        print("CREATE ({})-[:MOTHER]->({})".format(m,p))
        print("WITH {},{}".format(m,p))
        last_relationship = m
        #print "RETURN m,p"
    if person['Father'] is not '':
        print("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'".format(f,p,f,person['Father'],p,person['Name']))
        print("CREATE ({})-[:FATHER]->({})".format(f,p))
        print("WITH {},{}".format(f,p))
        last_relationship = f
        #print "RETURN m,p"
    if person['Married to'] is not '':
        print("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'".format(s,p,s,person['Married to'],p,person['Name']))
        print("CREATE ({})-[:MARRIED]->({})".format(s,p))
        print("WITH {},{}".format(s,p))
        last_relationship = s

print(f"RETURN {last_relationship or ''}")

In [ ]:
len(people)

In [ ]:
people[97]

In [ ]:
from neo4j.v1 import GraphDatabase

uri = "bolt://localhost:7687"
driver = GraphDatabase.driver(uri, auth=("neo4j", "aJZ=Ecq4"))

def print_married_to(name):
    with driver.session() as session:
        with session.begin_transaction() as tx:
            for record in tx.run("MATCH (a:Person)-[:MARRIED]->(f) "
                                 "WHERE a.name = {name} "
                                 "RETURN f.name", name=name):
                print(record["f.name"])

print_married_to("Joseph Armstrong")

In [10]:
%pip install neo4j

%pip install neo4j-driver

Collecting neo4j
  Downloading neo4j-5.28.1-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: pytz in /Users/chadarmstrong/Obsidian/Obsidian Vault/.conda/lib/python3.11/site-packages (from neo4j) (2023.3.post1)
Downloading neo4j-5.28.1-py3-none-any.whl (312 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 312.3/312.3 kB 6.9 MB/s eta 0:00:0000:01
Installing collected packages: neo4j
Successfully installed neo4j-5.28.1
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: neo4j-driver in /Users/chadarmstrong/Obsidian/Obsidian Vault/.conda/lib/python3.11/site-packages (5.28.1)
Requirement already satisfied: pytz in /Users/chadarmstrong/Obsidian/Obsidian Vault/.conda/lib/python3.11/site-packages (from neo4j-driver) (2023.3.post1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
def make_person(person):
    #print(person)
    statement = ("CREATE (" + make_person_id(person['Name']) + ":Person {name:'{name}', birth_date:'{birth_date}', "
                 "birth_location:'{birth_location}', "
                 "death_date:'{death_date}', death_location:'{death_location}'})")

    with driver.session() as session:
        with session.begin_transaction() as tx:
            result = tx.run(statement, {"person_id": make_person_id(person['Name']),
                                "name": person['Name'],
                                "birth_date": person['Born'],
                                "birth_location": person['Born Location'],
                                "death_date": person['Died'],
                                "death_location": person['Died Location']})
            print('Created ' + person['Name'])

# for person in people[0:10]:
#     make_person(person)

# for person in people:
#     print "CREATE (" + make_person_id(person['Name']) + \
#     ":Person {name:'" + person['Name'] + "', birth_date:'" + person['Born'] + "', birth_location:'" + \
# person['Born Location'] + "', death_date:'" + person['Died'] + "', death_location:'" + person['Died Location'] + "'})"

In [ ]:
def make_relationships(person):
    p = make_person_id(person['Name'])
    m = make_person_id(person['Mother'])
    f = make_person_id(person['Father'])
    s = make_person_id(person['Married to'])

    with driver.session() as session:
        with session.begin_transaction() as tx:
            if person['Mother'] is not '':
                r = m
                tx.run("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'"
                        " CREATE ({})-[:MOTHER]->({}) WITH {},{}"
                        " RETURN {},{}".format(r,p,r,person['Mother'],p,person['Name'],r,p,r,p,r,p))
                print("{} - :MOTHER -> {}".format(r,p))
            if person['Father'] is not '':
                r = f
                tx.run("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'"
                        " CREATE ({})-[:FATHER]->({}) WITH {},{}"
                        " RETURN {},{}".format(r,p,r,person['Father'],p,person['Name'],r,p,r,p,r,p))
                print("{} - :FATHER -> {}".format(r,p))
            if person['Married to'] is not '':
                r = s
                tx.run("MATCH ({}:Person), ({}:Person) WHERE  {}.name = '{}' and {}.name = '{}'"
                        " CREATE ({})-[:MARRIED]->({}) WITH {},{}"
                        " RETURN {},{}".format(r,p,r,person['Married to'],p,person['Name'],r,p,r,p,r,p))
                print("{} - :MARRIED -> {}".format(r,p))

# for person in people[0:10]:
#     make_relationships(person)

In [ ]:
import csv
from neo4j import GraphDatabase

localhost = False

if localhost:
    uri = "bolt://localhost:7687"
    driver = GraphDatabase.driver(uri, auth=("neo4j", "aJZ=Ecq4"))
else:
    uri = "bolt://52.205.81.5:7687"
    driver = GraphDatabase.driver(uri, auth=("neo4j", "7i=fBzYZ"))

with open('/Users/chada/Desktop/Archive/Programming/Node/geneology/data/Geneology.csv') as csv_file:
    people = list(csv.DictReader(csv_file))

def deleteAll():
    with driver.session() as session:
        with session.begin_transaction() as tx:
            result = tx.run('MATCH (n) DETACH DELETE n')
            print('Deleted everything!')

def make_person_id(name):
    return name.lower().replace(' ','_').replace('.','').replace('(','').replace(')','').replace('-','') \
    .replace('"','').replace("'",'').replace('?','').replace('\\','').replace('’','').replace('“','') \
    .replace('”','')

def make_person(person):
    #print(person)
    statement = ("CREATE (" + make_person_id(person['Name']) + ":Person {name:{name}, gender:{gender}, birth_date:{birth_date}, "
                 "birth_location:{birth_location}, "
                 "death_date:{death_date}, death_location:{death_location}})")

    with driver.session() as session:
        with session.begin_transaction() as tx:
            result = tx.run(statement, {"person_id": make_person_id(person['Name']),
                                "name": person['Name'],
                                "gender": person['Gender'],
                                "birth_date": person['Born'],
                                "birth_location": person['Born Location'],
                                "death_date": person['Died'],
                                "death_location": person['Died Location']})
            print('Created ' + person['Name'])


def make_relationships(person):
    p = make_person_id(person['Name'])
    m = make_person_id(person['Mother'])
    f = make_person_id(person['Father'])
    s = make_person_id(person['Married to'])

    with driver.session() as session:
        with session.begin_transaction() as tx:
            if person['Mother'] != '':
                r = m

                query = (
                    "MATCH (r:Person), (p:Person) "
                    "WHERE r.name = $mother_name AND p.name = $person_name "
                    "CREATE (r)-[:MOTHER]->(p) "
                    "RETURN r, p"
                )
                tx.run(query, mother_name=person['Mother'], person_name=person['Name'])
                print(f"{r} - :MOTHER -> {p}")

                if person['Gender'] == 'Male':
                    query = (
                        "MATCH (p:Person), (r:Person) "
                        "WHERE r.name = $mother_name AND p.name = $person_name "
                        "CREATE (p)-[:SON]->(r) "
                        "RETURN p, r"
                    )
                    tx.run(query, mother_name=person['Mother'], person_name=person['Name'])
                    print(f"{p} - :SON -> {r}")
                else:
                    query = (
                        "MATCH (p:Person), (r:Person) "
                        "WHERE r.name = $mother_name AND p.name = $person_name "
                        "CREATE (p)-[:DAUGHTER]->(r) "
                        "RETURN p, r"
                    )
                    tx.run(query, mother_name=person['Mother'], person_name=person['Name'])
                    print(f"{p} - :DAUGHTER -> {r}")

            if person['Father'] != '':
                r = f

                query = (
                    "MATCH (r:Person), (p:Person) "
                    "WHERE r.name = $father_name AND p.name = $person_name "
                    "CREATE (r)-[:FATHER]->(p) "
                    "RETURN r, p"
                )
                tx.run(query, father_name=person['Father'], person_name=person['Name'])
                print(f"{r} - :FATHER -> {p}")

                if person['Gender'] == 'Male':
                    query = (
                        "MATCH (p:Person), (r:Person) "
                        "WHERE r.name = $father_name AND p.name = $person_name "
                        "CREATE (p)-[:SON]->(r) "
                        "RETURN p, r"
                    )
                    tx.run(query, father_name=person['Father'], person_name=person['Name'])
                    print(f"{p} - :SON -> {r}")
                else:
                    query = (
                        "MATCH (p:Person), (r:Person) "
                        "WHERE r.name = $father_name AND p.name = $person_name "
                        "CREATE (p)-[:DAUGHTER]->(r) "
                        "RETURN p, r"
                    )
                    tx.run(query, father_name=person['Father'], person_name=person['Name'])
                    print(f"{p} - :DAUGHTER -> {r}")

            if person['Married to'] != '':
                r = s

                query = (
                    "MATCH (r:Person), (p:Person) "
                    "WHERE r.name = $spouse_name AND p.name = $person_name "
                    "CREATE (r)-[:MARRIED]->(p) "
                    "RETURN r, p"
                )
                tx.run(query, spouse_name=person['Married to'], person_name=person['Name'])
                print(f"{r} - :MARRIED -> {p}")

deleteAll()

#here is a comment
num_rows_to_process = 500

for person in people[0:num_rows_to_process]:
    make_person(person)

for person in people[0:num_rows_to_process]:
    make_relationships(person)

In [ ]:
def deleteAll():
    with driver.session() as session:
        with session.begin_transaction() as tx:
            result = tx.run('MATCH (n) DETACH DELETE n')
            print('Deleted everything!')

deleteAll()

In [ ]:
def getEverything():
    with driver.session() as session:
        with session.begin_transaction() as tx:
            for record in tx.run('MATCH (n) OPTIONAL MATCH (n)-[r]->(m) RETURN n, r, m'):
                if record['r'] is not None:
                    record_r = record['r'].type
                else:
                    record_r = 'None'
                if record['m'] is not None:
                    record_m = record['m']['name']
                else:
                    record_m = 'None'

                #print(record)
                print('{} is {} to {}'.format(record['n']['name'], record_r, record_m))

getEverything()